flathub/info.febvre.Komikku

info.febvre.Komikku.json
Data (SQLite DB and images scans) are now stored in XDG_DATA_HOME
(~/.var/app/info.febvre.Komikku/data) instead of ~/Komikku
=> New release 0.1.1

info.febvre.Komikku.json
Pager focus is now correctly restored when menu is closed (useful for keypad navigation)
=> New release 0.7.1

info.febvre.Komikku.json
[Reader] Re-allow page scaling in Vertical reading mode (disabled by mistake in 0.22.0)
=> New release 0.22.1

info.febvre.Komikku.json, python3-keyring.json
- Refined the ability to add comics via the command line: more servers supported
- [Explorer] Search: Add button to open server's website in browser
- [Explorer] Servers list: Add a 'key' icon when a server requires a user account
- [Explorer] Manga card: Add last chapter
- [Servers] Add Komga (Free and open source comics/mangas media server)
- [Servers] Add View Comics (EN)
- [Servers] NineManga: Update
- [Servers] Scan Manga: Update
=> New release 0.26.0

info.febvre.Komikku.json, python3-brotli.json
- [Library] Add Categories to organize the library
- [Servers] Add Read Comics Online (EN)
- [Servers] Komga: Add sync (read progress) with server
- [Servers] JapScan: Partial fix (Webtoons chapters in single page are not handled)
- [Servers] MangaSee: Fix page download for chapters with decimals in name
- [Servers] Reaper Scans: Update
- [Servers] Scan Manga: Skip chapters coming from external servers
- [Servers] Tutto Anime Manga: Update
- [L10n] Add Italian translation
- [L10n] Update German translation
=> New release 0.27.0

info.febvre.Komikku.json
- Several UI changes to improve scaling on small devices screens
- [Library] Add categories edition in bulk (via multiple selection mode)
- [Reader] Fix memory leaks
- [Explorer] Allow search in servers list
- [Explorer] Added possibility to pin favorite servers
- [Updater] Prevents updating of comics whose server is disabled
- [Keyring] Improved SecretService detection
- [Servers] Add AllHentai (RU)
- [Servers] Add CatManga aka Black Cat Scanlations (EN)
- [Servers] Add Dongman Manhua (ZH Hans)
- [Servers] Add Madara (multi servers): Aloalivn (EN), Apoll Comics (ES), Wakascan (FR)24hRomance (EN), AkuManga (AR), ArazNovel (TR), Argos Scan (PT), Atikrost (TR)
- [Servers] Add MangaFreak (EN)
- [Servers] Pepper&amp;Carrot: Fix pages order
- [Servers] Scantrad …
=> New release 0.28.1

info.febvre.Komikku.json
- [Library] Thumbnails: Fix rendering of servers logos and badges on mobile devices
- [Card] Fixed synopsis display when it contains HTML
- [Reader] Add option to hide page numbering
- [Reader] Fixed pager jumps when page rendering is retried
- [Explorer] Servers: Don't show Pinned when empty
- [Servers] Add Best Manga [RU]
- [Servers] Add Bilibili [EN]
- [Servers] Add Tapas [EN]
=> New release 0.32.0

info.febvre.Komikku.json
- [Card] Add keyboard navigation outside of selection mode
- [Servers] CatManga: Disable
- [Servers] Lelscan-VF: Disable
- [Servers] ReaperScansFR: Disable
- [Servers] 24hRomance: Update
- [Servers] Asura Scans [EN/TR]: Update
- [Servers] Colored Manga (Colored Council): Update
- [Servers] Phoenix Fansub [ES]: Update
- [Servers] Raw Manga [JA]: Update
- [Servers] Rawkuma [JA]: Update
- [Servers] Submanga: Update
- [L10n] Update French and Spanish translations
=> New release 0.36.0

info.febvre.Komikku.json
- Add `Quit` shortcut action (Ctrl+Q)
- [Servers] Fixed loading of images in `webp` format
- [Servers] Add GTO TGS [IT]
- [Servers] Add Phoenix Scans [IT]
- [Servers] Edelgarde Scans: Disabled
- [Servers] Hatigarm Scans: Disabled
- [Servers] Leomanga: Update
- [Servers] LupiTeam: Update
- [Servers] Nine Manga: Improved images loading
- [Servers] Wakascan: Disabled
=> New release 0.37.0

info.febvre.Komikku.json, python3-emoji.json
- [Reader] Webtoon reading mode: Add srcolling with Page Up and Page Down keys
- [Explorer] Global search: Put servers without results at end
- [Preferences] Advanced: Add new option to disable GTK animations (useful with E Ink e-readers)
- [Servers] Add 3asq (مانجا العاش) [AR]
- [Servers] Apoll Comics: Update
- [Servers] Best Manga: Update
- [Servers] Lector Manga (Leomanga): Update
- [Servers] LeviatanScans: Update
- [Servers] Mangaowl: Update
- [Servers] Remanga: Update
- [Servers] Xoxocomics: Update
- [Servers] Kirei Cake: Disable
=> New release 1.5.0

info.febvre.Komikku.json
- [Explorer] Add `Latest Updates` (not available for all compatible servers yet)
- [Servers] Add Reaper Scans AR, FR, ID and TR
- [Servers] Re-enables Tutto Anime Manga (TAM) [IT]
- [Servers] Atikrost: Update
- [Servers] LeviatanScans [EN]: Update
- [Servers] Manga-Scantrad: Update
- [Servers] Mangaowl: Update
- Brings new French and Brazilian Portuguese translations
=> New release 1.7.0

info.febvre.Komikku.json
- [UI] Added ability to go back with <ALT+Left> shortcut
- [Reader] Added ability to navigate foward with <SPACE> key
- [Servers] Guya.moe: Update
- [Servers] Manga/in/ua: Update
- [Servers] MangaFreak: Update
- [Servers] MangaHub: Update
- [Servers] MangaLib: Update
- [Servers] Mangas Origines: Update
- [Servers] Mangas.in: Update
Beware, all servers that contain explicit sexual content or nudity, such as hentai, ecchi and yaoi/yuri are now tagged NSFW.
=> New release 1.12.0

info.febvre.Komikku.json
Bugfix release
Fixed a bug that caused the loss of some pinned servers in the Explorer (it's certainly too late for those who have updated to version 1.12.0).
BEWARE, since 1.12.0, all servers that contain explicit sexual content or nudity, such as hentai, mature, ecchi or yaoi/yuri are now tagged NSFW (18+).
=> New release 1.12.1

info.febvre.Komikku.json
Bugfix release: A regression prevented detection of the SecretService backend used for the keyring
=> New release 1.24.1 (bugfix)

info.febvre.Komikku.json, python3-dateparser.json
- [Reader] RTL/LTR/Vertical pager: Improved initial positioning of images when pages are scrollable
- [Reader] RTL/LTR/Vertical pager: Fixed bug preventing swipe gesture navigation on some circumstance with touch screen devices
- [Reader] Webtoon pager: Improved scrolling smoothness
- [Reader] Pagers: Improved reading progress saving
- [Servers] Added MangaReader.to [EN/FR/JA/KO/ZH_HANS]
- [Servers] Local: Retrieved more info from ComicInfo.xml when available in the archive
- [Servers] WEBTOON: Update
- [L10n] Updated Spanish translation
=> New release 1.29.0

info.febvre.Komikku.json
- [Reader] Used best image scaling filter based on zoom value
- [Reader] Fixed memory leaks
- [Reader] RTL/LTR/Vertical pager: Fixed unzoom by double tap/click
- [Reader] Webtoon pager: Improved detection when first or last chapter is reached
- [Servers] Grise Bouille [FR]: Update
- [L10n] Updated Chinese (Simplified), Portuguese, Portuguese (Brazil) and Russian translations
=> New release 1.34.0

info.febvre.Komikku.json
- [Reader] Used best image scaling filter based on zoom value
- [Reader] Fixed memory leaks
- [Reader] RTL/LTR/Vertical pager: Fixed unzoom by double tap/click
- [Reader] Webtoon pager: Improved detection when first or last chapter is reached
- [Servers] Grise Bouille [FR]: Update
- [L10n] Updated Chinese (Simplified), Portuguese, Portuguese (Brazil) and Russian translations
=> New release 1.34.1

info.febvre.Komikku.json
- [Reader] Used best image scaling filter based on zoom value
- [Reader] Fixed memory leaks
- [Reader] RTL/LTR/Vertical pager: Fixed unzoom by double tap/click
- [Reader] Webtoon pager: Improved detection when first or last chapter is reached
- [Servers] Grise Bouille [FR]: Update
- [Servers] Toonily [EN]: Fix
- [L10n] Updated Chinese (Simplified), Finnish, Portuguese, Portuguese (Brazil) and Russian translations
=> New release 1.34.2

info.febvre.Komikku.json
- [Reader] RTL/LTR/Vertical pager: Speed up white borders cropping
- [Servers] Izneo: Update
- [Servers] LegacyScans (FR): Update
- [Servers] Manhuaus (EN): Fixed manga statuses
- [Servers] MonkeyUser (EN): Update
- [Servers] NHentai (EN/JA/ZH): Added covers in searches results
- [Servers] Mangadoor (ES): Disable
=> New release 1.36.0

info.febvre.Komikku.json
- [Downloader] Improved error notification
- [Updater] Improved notifications
- [Updater] Prevent manga update from being scheduled while it's being updated
- [Servers] Armoni Scans (TR): Disable
- [Servers] Komga: Fixed missing covers in search
- [Servers] Manhuaus (EN): Update
- [Servers] Manhwa Hentai (EN): Update
- [Servers] Tapas (EN): Update
- [L10n] Updated Chinese (Traditional), French, Russian, Spanish, Turkish translations
=> New release 1.38.0

info.febvre.Komikku.json
This version fixes a regression in Updater. During batch updates, an unwanted "No new chapters" notification was sent for every manga without changes.
Changes in version 1.38.0
- [Downloader] Improved error notification
- [Updater] Improved notifications
- [Updater] Prevent manga update from being scheduled while it's being updated
- [Servers] Armoni Scans (TR): Disable
- [Servers] Komga: Fixed missing covers in search
- [Servers] Manhuaus (EN): Update
- [Servers] Manhwa Hentai (EN): Update
- [Servers] Tapas (EN): Update
- [L10n] Updated Chinese (Traditional), French, Russian, Spanish, Turkish translations
=> New release 1.38.1

info.febvre.Komikku.json
This version fixes a bug in Preferences. Switching NFSW content switches caused the application to crash.
Changes in version 1.40.0
- [UX] Refined visuals taking advantage of the new capabilities of GNOME 46
- [Servers] Added Lelmanga (FR)
- [Servers] Added Lelscan (FR)
- [Servers] Added Night scans (EN)
- [Servers] Comic Book Plus (EN): Fixed search
- [Servers] MANGA Plus by SHUEISHA: Update
- [Servers] MangaDex: Added Tags filter
- [Servers] MangaLib (RU): Update
- [Servers] Mangaowl (EN): Update
- [Servers] Jpmangas (FR): Disabled
- [Servers] Reaper Scans (pt_BR): Disabled
- [Servers] Scan FR: Disabled
- [Servers] Scan Manga (FR): Disabled
- [L10n] Updated French, Russian, Spanish and Turkish translations
=> New release 1.40.1

info.febvre.Komikku.json
This version fixes:
- A regression in Explorer, pinned servers list was no longer cleared when it was refreshed
- Wrong chapters order in Perf Scan (FR) server
Changes in previous version 1.41.0:
- [Servers] Added ComicExtra (EN)
- [Servers] Mangas.in (ES: Update
- [L10n] Updated French, Russian, Spanish and Turkish translations
=> New release 1.41.1

info.febvre.Komikku.json
This version fixes a bug that prevented some server logos from being displayed.
Changes in version 1.45.0:
- [Webview] Improved Cloudflare user challenge completion
- [Servers] Added Existential Comics (EN)
- [Servers] Added Manga Demon (EN)
- [Servers] Added MangaWeebs (EN)
- [Servers] Added Webtoon TR
- [Servers] Armoni Scans (Asura Scans TR): Reenabled
- [Servers] Atikrost (TR): Reenabled
- [Servers] MangaFreak (EN): Update
- [Servers] Nine Manga (EN/PT_BR/DE/ES/FR/IT/RU): Update
- [L10n] Added Vietnamese translation
- [L10n] Updated French, German, Portuguese, Spanish and Russian translations
=> New release 1.45.1 (bugfix)

info.febvre.Komikku.json
- Fixed display of covers in animated GIF format
- Fixed memory leaks
- [Servers] Added Manga Mana (FR)
- [Servers] Tecno Scan (ES): Reenable
- [Servers] Anteiku Scans (FR): Update
- [Servers] ComicExtra (EN): Update
- [Servers] ED Scanlation (FR): Update
- [Servers] Kewn Scans (EN): Update
- [Servers] MangaWeebs (EN): Update
- [Servers] Scylla Comics (EN): Update
- [Servers] Starbound Scans (FR): Update
- [L10n] Update Portuguese (Brazil) translation
=> New release 1.58.0

info.febvre.Komikku.json
- [Servers] Added Asura Scans For Free (EN)
- [Servers] MangaDex: Ignored externals and empty chapters
- [Servers] MangaDex: Added Genres filter
- [Servers] MangaHub: Avoided exceeding API rate limiting
- [Servers] MangaLib (RU): Update
- [Servers] Mangareader (to): Fixed decoding of scrumbled images
- [L10n] Updated Finnish, Portuguese (Brazil), Russian, Spanish, Swedish and Ukrainian translations
=> New release 1.66.0

info.febvre.Komikku.json
- [Servers] Manga Demon (EN): Update
- [Servers] Neko Scans (ES): Update
- [Servers] Sinensistoon (pt_BR): Renamed SCtoon (fusion with Cerise Scan)
- [Servers] Cerise Scan (pt_BR): Disabled
- [Servers] MangaLife (EN): Disabled
- [Servers] MangaSee (EN): Disabled
- [L10n] Added Czech translation
=> New release 1.69.0

info.febvre.Komikku.json
GNOME 48 (libadwaita 1.7.0)
- [Library] Added ability to update with &lt;Ctrl+r&gt; shortcut
- [Card] Info: Improved display of Genres using badges
- [Servers] Added MangaBin (EN)
- [Servers] Added Vortex Scans For Free (EN)
- [Servers] Manhuaus (EN): Update
- [Servers] Remanga (RU): Update
- [L10n] Added Hungarian translation
=> New release 1.73.0

info.febvre.Komikku.json
- [Card] Details page: Redesign
- [Servers] Local: Added support of CBT archive format (TAR)
- [Servers] Added Blue Solo (FR)
- [Servers] SMBC (EN): Re-enabled
- [Servers] Poseidon Scans (FR): Disabled
- [L10n] Updated Arabic, Bulgarian, Catalan and Portuguese (Brazil) translations
=> New release 1.78.0

info.febvre.Komikku.json, python3-dateparser.json, python3-modern-colorthief.json
- [UX] Refined visuals taking advantage of the new capabilities of GNOME 49
- [UI] Switching to Glycin (image loading framework)
- [Reader] Webtoon pager: Fixed small gap between pages
- [Servers] Grise Bouille (FR): Update
- [Servers] Neko Scans (ES): Disabled
- [Servers] Qi Scans (Night scans): Update
- [L10n] Updated French, Portuguese, Portuguese (Brazil) and Ukrainian translations
=> New release 1.88.0
