flathub/info.febvre.Komikku

- info.febvre.Komikku.json
- Add the Portuguese (Brazil) translation
- Add a new server: Central de Mangas (Portuguese)
> New release r0.1.2

- info.febvre.Komikku.json
> New release 0.1.3

- info.febvre.Komikku.json
- New servers: NineManga Russian, Webtoon Indonesia and Webtoon Thai
- For all servers that allow it, most popular mangas are now offered as starting search results.
> New release 0.2.0

- info.febvre.Komikku.json
- python3-cloudscraper.json
- Added Dragon Ball Multiverse (DBM) server
- Fixes in Japscan server (search still broken)
> New release 0.3.0

- info.febvre.Komikku.json
> New release 0.3.1

- info.febvre.Komikku.json
- python3-cloudscraper.json
- New preference: Automatically update library at startup
- Fix in Mangakawaii server (Cloudflare problem)
> New release 0.4.0

- info.febvre.Komikku.json
> New release 0.5.0

- info.febvre.Komikku.json
- A bug fix in change of reading direction
- A bug fix in Pepper&Carrot
> New release 0..5.1

- info.febvre.Komikku.json
- python3-cloudscraper.json
- New preference: Servers languages
- Bug fixes in Scantrad France and DB Multiverse
> New release 0.6.0

- info.febvre.Komikku.json
- Ninemanga: Fixed missing chapters issue (EN, BR, DE, ES, IT)
- Pepper&Carrot: Fixed chapters update
- Pepper&Carrot: Added missing Cover and Credits pages
> New release 0.6.1

- info.febvre.Komikku.json
Fixed Manganelo and WEBTOON servers
> New release 0.6.2

- info.febvre.Komikku.json
- python3-cloudscraper.json
- Added 'Vertical' reading direction
- Added 'Night Light' preference
> New release 0.7.0

- info.febvre.Komikku.json
- python3-unidecode.json
- Fixed 'Night Light' preference
- Fixed JapScan server search
> New release 0.7.2

- info.febvre.Komikku.json
- python3-pure-protobuf.json
- Added MANGA Plus server (EN, [ES)
- Added Jaimini's Box (EN)
> New release 0.8.0

- info.febvre.Komikku.json
Jaimini's Box server: Fixed mangas with an adult alert
> New release 0.8.1

- info.febvre.Komikku.json
- Added a Download Manager
- [Manga] Improved chapters download
- [Reader] Vertical reading direction: Added scrolling with UP and DOWN keys
- [Reader] Added a Retry button when a image load failed
- [Servers] Removed Manga Rock (server has closed)
- [Servers] Minor fix in xkcd
- [Servers] MangaDex: Added 15 languages
> New release 0.10.0

- info.febvre.Komikku.json
- Added Desu server (RU)
- Added the Russian translation
- Updated the Brazilian Portuguese translation
- Fixed a bug in manga updater
> New release 0.11.0

- info.febvre.Komikku.json
> New release 0.11.1

- info.febvre.Komikku.json
- [Manga] Fixed the unread action of chapters
- [Reader] Cursor hiding during keyboard navigation
- [Reader] Arrow scrolling in every reading directions
- [Reader] Added white borders crop
- [Servers] Added Kirei Cake (EN)
- [Servers] Added Read Manga, Mint Manga and Self Manga (RU)
- [Servers] Updated Mangakawaii domain
- [Servers] Fixed JapScan search (using DuckDuckGo Lite)
- Added back navigation with Escape key
- Added abilility to add manga by ID using keyword "id:&lt;id&gt;" (useful with MangaDex)
- Various bugs fixes
> New release 0.12.0

- info.febvre.Komikku.json
- [Servers] Mangakawaii: Fixed manga cover
- Improved manga update
> New release 0.12.1

- info.febvre.Komikku.json
- python3-cloudscraper.json
- [Reader] Fix crash with corrupt or empty images
- [Settings] Add servers settings
- [Servers] Add Union Mangás (PT)
- [Servers] Add MangaLib and HentaiLib (RU)
- [Servers] Add Edelgarde Scans (EN)
- [Servers] Add Hunlight Scans (EN)
- [Servers] Add Leviatan Scans (EN, ES)
- [Servers] Add One Shot Scans (EN)
- [Servers] Add Reaper Scans (EN)
- [Servers] Add The Nonames Scans (EN)
- [Servers] Add Zero Scans (EN)
- [Servers] Hatigarm Scans: new server version
- [Servers] Scantrad France: Fix
- [Servers] MangaDex: Added ability to log in
- [Servers] Read Manga: Fixes
- Improved manga update
> New release 0.13.0

- info.febvre.Komikku.json
- python3-cloudscraper.json
- [Reader] Add 'Original Size' scaling
- [Reader] Several fixes in keyboard navigation
- [Settings] Library: Add new option 'Auto Download of New Chapters'
- [Settings] Library: Add new option 'Long Strip Detection' (MangaDex, MangaNelo, Mangakawaii, JapScan and Union Mangás)
- [Servers] JapScan: Fix search and images loading
- [Servers] MangaLib: Fix images loading
- [Servers] Submanga: Update of domain
> New release 0.14.0

- info.febvre.Komikku.json
- [Library] Add search by genre (exact match)
- [Library/Chapters] Add range selection: long press on an item then long press on another to select everything in between
- [Chapters] Fully cached/read chapters are now marked as "Downloaded"
- [Reader] Improve keyboard navigation
- [Reader] Improve pages transition
- [Servers] Add Crunchyroll (EN): a Premium account is required
- [Servers] Scantrad France: Add Most populars
- Improve manga update
- New icon
> New release 0.15.0 (runtime version fix)

- info.febvre.Komikku.json
- python3-cloudscraper.json
[Library] Faster chapters list rendering
[Library] Faster read/unread state toggling with long chapters selections
[Library] Reduce memory used by covers
[Servers] MangaSee: Fix manga with chapters grouped by seasons
[Servers] Jaimini's Box: Several fixes[Servers] MangaLib: Several fixes
> New release 0.15.1

- info.febvre.Komikku.json
- python3-cloudscraper.json
- [Library/Readers] Add support of animated GIFs
- [Library] Add &lt;Control&gt;+F shortcut: Enter search mode
- [Library/Manga/Download Manager] Add &lt;Control&gt;+A shortcut: Select all
- [Library/Manga/Download Manger] Add &lt;Control&gt;+Click and &lt;Shift&gt;+Click shortcuts: Enter selection mode
- [Download Manager] Add range selection: long press on an item then long press on another to select everything in between
- [Manga] Add chapters scanlators support (MangaDex only)
- [Servers] Add Izneo (DE, EN and FR) and Yieha (NL): a account is required
> New release 0.16.0

- info.febvre.Komikku.json
Fix 2 critical bugs (app crashs)
> New release 0.16.1

- info.febvre.Komikku.json
- python3-cloudscraper.json
- [Preferences] New UI
- [Servers] MangaNelo: Fix images loading
- [Servers] Disable Jaimini's Box
> New release 0.17.0

- info.febvre.Komikku.json
- python3-cffi.json
- python3-cloudscraper.json
- python3-dateparser.json
- python3-importlib-metadata.json
- python3-keyring.json
- python3-pillow.json
- python3-wheel.json
- [Library] Press &lt;Enter&gt; opens first manga in search
- [Library] Disable range selection when in search mode
- [Library/Chapters/Download manager] Enter selection mode with Right click
- [Reader] Two new navigation types: mouse scroll, 2-fingers swipe gesture
- [Reader] New 'Save Page' action
- [Servers] Fix and improve credentials storage
- [servers] Crunchyroll: Fix login
- [Servers] Re-enable Jaimini's Box
- [Servers] Manga Eden: Fix downloading of images
- [Servers] Manga Plus: Add manga 'Status' info
- [Servers] Manga Plus: Can't get manga info of some manga
- [Servers] MangaDex: Fix new chapters not appearing
- [Servers] Webtoon: Fix search
- [Preferences] Add search
- Add Turkish translation
> New release 0.18.0

- info.febvre.Komikku.json
- Add HiDPI display support
- [Preferences] Use Handy.PreferencesWindow subpages to display Servers Languages and Servers Settings
> New release 0.19.0

- info.febvre.Komikku.json
- python3-cloudscraper.json
- [Library] Search: Add filter options (Downloaded, Unread, Recent)
- [Preferences] The window and its subpages can now be closed with Esc key
- [Servers] Add Dynasty (EN)
- [Servers] Add 'Lupi Team' and 'Tutto Anime Manga' (IT)
- [Servers] Add VizManga (EN): an account is required
- [Servers] Disable Jaimini's Box (definitely closed)
- [L10n] Add German translation
> New release 0.20.0

- info.febvre.Komikku.json
- python3-cffi.json
- python3-dateparser.json
- python3-keyring.json
As explained in title, update to latest version.
> Update to 0.21.1

- info.febvre.Komikku.json
- [Library] Allow bulk downloading of manga, as well as marking all chapters as (un)read
- [Card] Chapters list: Add sort by date
- [Reader] Add new pager for Webtoons: Vertical smooth/continuous scrolling (a.k.a. infinite canvas)
- [Download Manager] Adding downloads: Improve responsiveness
- [Preferences] Library: Add new option to allow user to enable/disable servers with NSFW only content
- [Servers] Add Mangahub
- [Servers] Add NHentai
- [Servers] Add Readmanhwa
- [Servers] Central de Mangás: Update
- [Servers] Crunchyroll: Update
- [Servers] Izneo: Update
- [Servers] MangaNelo: Update
- [Servers] Dynasty: Improvements
- [L10n] Update French and German translations
> New release 0.22.0

- info.febvre.Komikku.json
- [Add dialog] Add Back navigation between pages via Esc key
- [Add dialog] Search page: Give keyboard focus to search entry when a printable character is typed
- [Card] Add 'Resume read' button
- [Servers] Add Xoxocomics (EN)
- [Servers] MangaDex: Update to API v2 (more stable)
- [Servers] ScanOnePiece: Update
- [Servers] Self Manga: Update
- [Servers] Disable Leviatan Scans (ES)
> New release 0.23.0

- info.febvre.Komikku.json
- Added ability to add comics via the command line
- [Servers] Add Scan Manga (FR)
- [Servers] Scantrad France: Update
- [Servers] Mangahub: Fixed pages wrong order
> New release 0.25.0

- info.febvre.Komikku.json
> New release 0.25.1

- info.febvre.Komikku.json
[Preferences] Fixed a bug in saving logins credentials
> New release 0.26.1

- info.febvre.Komikku.json
- python3-cffi.json
- python3-requests.json
- [Library] Displayed currently selected category in subtitle
- [Library] Add 'Uncategorized' category
- [Servers] Mangadex: The long-awaited comeback
- [Servers] MangaNato: Update (previously called MangaNelo). Previous manga and chapters won’t work after this
update and need to be readded.
- [Servers] MangaHub: Update
- [L10n] Update French and German translation
> New release 0.29.0

- info.febvre.Komikku.json
[Library] Fix bug preventing app startup (empty library only)
> New release 0.29.1

- info.febvre.Komikku.json
- python3-cloudscraper.json
> New release 0.29.2

- info.febvre.Komikku.json
- [UI] Major redesign (except Library and Reader)
- [Card] Fixed chapters list scrolling on mobile devices
- [Reader] Fix fullscreen/unfullscreen on mobile devices
- [Reader] Fixed navigation between pages on mobile devices
- [Reader] Fixed zoom on mobile devices
- [Servers] Add Colored Council [EN]
- [Servers] Add Danke fürs Lesen [EN]
- [Servers] Add Guya [EN]
- [Servers] Add Hachirumi [EN]
- [Servers] Add Jpmangas [FR]
- [Servers] Add Magical Translators [EN/PL]
- [Servers] Read Manga server: Update
- [Servers] Read Comic Online: Update
- [Servers] Webtoon: Update
- [Servers] Pepper&amp;Carrot: Update
- [Servers] Komga: Fix crashes when viewing manga from offline
- [L10n] Add Polish translation
- [L10n] Add Spanish …
> New release 0.31.0

- info.febvre.Komikku.json
- [Reader] Controls overlay: Fix a bug in pages slider
- [Servers] Add MangaKawaii [EN]
- [Servers] Guya: Update
- [Servers] MangaFreak: Add notification to notify user when webview failed to solve Cloudflare JS challenge
- [Servers] Tapas: Get dates while resolving chapters
- [L10n] Update Polish translation
> New release 0.33.0

- info.febvre.Komikku.json
> New release 0.33.1

- info.febvre.Komikku.json
- python3-beautifulsoup4.json
- [Servers] Add Asura Scans [EN, TR]
- [Servers] Add FR Scan [FR]
- [Servers] Add Lelscan-VF [FR]
- [Servers] Add Leomanga [ES]
- [Servers] Add Phoenix Fansub [ES]
- [Servers] Add Mangadoor [ES]
- [Servers] Add Mangas.in [ES]
- [Servers] Add Scan FR [FR]
- [Servers] Add Scan OP [FR]
- [Servers] Bilibili: Update
- [Servers] Jpmangas: Update
- [L10n] Update French and German translations
> New release 0.34.0

- info.febvre.Komikku.json
- [Servers] MANGA Plus by SHUEISHA: Update
- [Servers] Mangahub: Fixed bug when summary is missing
- [L10n] Update French and Polish translations
> New release 0.34.1

- info.febvre.Komikku.json
- [Servers] NHentai: Update
- [Servers] Webtoon: Update
- [L10n] Update German translation
> New release 0.36.1

- info.febvre.Komikku.json
- python3-cloudscraper.json
- python3-dateparser.json
- [Servers] Add Mangapill [EN]
- [Servers] FR Scan: Update
- [Servers] Jpmangas: Update
- [Servers] MangaFreak: Update
- [Servers] Mangas.in: Update
- [Servers] Scan Manga: Update
- [Servers] NHentai: Disable
> New release 0.39.0

- info.febvre.Komikku.json
- [Servers] Add Remanga [RU]
- [Servers] Add Manga.in.ua [UA]
- [Servers] FR Scan: Update
- [Servers] Lelscan-VF: Reenabled
- [Servers] Leomanga: Update
- [Servers] Madara (multi): Added filter in search to ignore novels
- [Servers] Mangas.in: Update
- [Servers] Rawkuma: Update
- [Servers] Scan FR: Update
- [Servers] Submanga: Disabled
- [L10n] Update French translation
> New release 0.40.0

- info.febvre.Komikku.json
- python3-cloudscraper.json
- [Servers] Add Aralos BD [FR]
- [Servers] Add Manga-Scantrad [FR]
- [Servers] Add Mangas Origines [FR]
- [Servers] Add Mangaowl [EN]
- [Servers] Asura Scans: Update (EN+TR)
- [Servers] BILIBILI COMICS: Update
- [Servers] MangaHub: Update
- [Servers] Mangas.in: Fix `Most populars` order
- [Servers] Phoenix Fansub: Update
- [Servers] Rawkuma: Update
- [Servers] ReadManhwa: Update
- [Servers] Union Mangás: Update
> New release 0.41.0

- info.febvre.Komikku.json
- Landscape covers (rare) are now converted to portrait
- [Reader] Webtoon reading mode: Bugfix
- [Reader] Fixed detection of 'read' chapters
- [Servers] MangaLife [EN]: Reenable
- [Servers] LeviatanScans [EN]: Reenable
- [Servers] Mangas Origines: Update
- [Servers] Reaper Scans [PT]: Update
- [Servers] Remanga: Update
- [Servers] Scan OP [FR]: Disable
- [Servers] Zero Scans: Disable
- [L10n] Add Simplified Chinese translations
- [L10n] Update Turkish translation
> New release 1.1.0

- info.febvre.Komikku.json
- python3-dateparser.json
- python3-rarfile.json
- [Reader] Improved Webtoon reading mode
- [Servers] Add Local server (CBZ/CBR archives)
- [Servers] Add Comc Book Plus [EN]
- [Servers] Reaper Scans [PT]: Update
- [Servers] Scan FR: Update
- [L10n] Update French and German translations
> New release 1.2.0

- info.febvre.Komikku.json
- python3-dateparser.json
- [Downloader] Improved download speed
- [Explorer] Add Global search
- [Servers] Aralos BD: Fixed search
- [Servers] Local: Fixed CBR archives reading bug (Flatpak only)
> New release 1.3.0

- info.febvre.Komikku.json
- Fixed app not starting on SteamOS (Steam Deck)
- [Library] Improved thumbnails badges
- [Reader] Improved double tap zoom on touch screens
- [Downloader] Bug fix
- [Updater] Bug fix
- [Servers] Local: Fixed wrong pages order with some archives
> New release 1.4.1

- info.febvre.Komikku.json
- New icon 🎉 Thank you to its author Tobias Bernard
- [Card] Chapters are now downloaded in ascending order of chapter numbers
- [Servers] Add Manga Tube [DE]
- [Servers] Lector Manga (Leomanga): Update
- [Servers] Mangapill: Update
- [L10n] Update French and Simplified Chinese translations
- Bugs fixes
> New release 1.6.0

- info.febvre.Komikku.json
Bug-fix release:
- Missing database indexes
- Disappearance of the categories toggle button after leaving the library
> New release 1.6.1

- info.febvre.Komikku.json
- [Reader] LTR, RTL, vertical pager: Added 2-finger zoom gesture
- [Reader] LTR, RTL, vertical pager: Improved double-tap zoom on touchscreens
- [Reader] LTR, RTL, vertical pager: Fixed page scrolling when scaling is `Original Size`
- [Servers] Add Toonily [EN]
- [Servers] Dynasty: Update
- [Servers] Golden Mangás: Update
- [Servers] Local: Repair
> New release 1.9.0

- info.febvre.Komikku.json
- [Library] Improved thumbnails appearance
- [Explorer] Various improvements in search
- [Reader] LTR, RTL, vertical pager: Improved page transition animation
- [Servers] Read Manga, AllHentai, Mint Manga, Self Manga: Update
- [A11y] Fixed keyboard navigation and added missing buttons tooltips
- [L10n] Update French and German translations
> New release 1.10.0

- info.febvre.Komikku.json
[Explorer] Global search: Bugfix
> New release 1.10.1

- info.febvre.Komikku.json
- python3-dateparser.json
- [UI] Use #f66151 color (orange) as app's accent color
- [Shortcuts] Add <Ctrl+f> in History and Explorer => Servers (toggles search entry)
- [Servers] Japscan: Update
- [Servers] Manga-Scantrad: Update
- [Servers] Raw Manga: Update
- [Servers] Read Comic Online: Update
- [L10n] Update French, German and Turkish translations
> New release 1.11.0

- info.febvre.Komikku.json
- [UI] Use #f66151 color (orange) as app's accent color
- [Shortcuts] Add <Ctrl+f> in History and Explorer => Servers (toggles search entry)
- [Servers] Japscan: Update
- [Servers] Manga-Scantrad: Update
- [Servers] Raw Manga: Update
- [Servers] Read Comic Online: Update
- [L10n] Update French, German and Turkish translations
> New release 1.11.1

- info.febvre.Komikku.json
- [UX] Added possibility to go back with mouse Back button
- [Library] Fixed range selection mode
- [Servers] Added FMTEAM [FR] (Scantrad France sucessor)
- [Servers] MangaDex: Added `Español (Latinoamérica)` language
- [Servers] Pepper&amp;Carrot: Added `Espéranto` language
- [Servers] Manga-Scantrad: Update
- [Servers] Scantrad France: Disable
- [Servers] Le Cercle du Scan: Added `Latest Updates`
> New release 1.14.0

- info.febvre.Komikku.json
- python3-dateparser.json
- [Explorer] Added ability to read from search results (new settings have been added in Preferences to manage cached data)
- [Reader] Fixed memory leaks
- [Servers] WEBTOON: Update
- [L10n] New Finnish and Indonesian translations
- [L10n] Update Portuguese (Brazil) and Spanish translations
> New release 1.16.0

- info.febvre.Komikku.json
- [Preferences] Disappearance of the `Dark Theme` setting in favor of a new `Theme` setting offering 3 choices (Light, Dark, Follow System)
- [Servers] Added Escaneos de Leviatan [ES]
- [Servers] Added Fr-Scan [FR]
- [Servers] Added MonkeyUser [EN]
- [Servers] Jpmangas: Update
- [Servers] Lelscan-VF: Update
- [L10n] Updated French, Indonesian, Portuguese (Brazil) and Spanish translations
> New release 1.19.0

- info.febvre.Komikku.json
- [Servers] Added Flame Scans [EN]
- [Servers] Added MangaHere [EN]
- [Servers] 3asq: Update
- [Servers] LeviatanScans: Update [EN/ES]
- [Servers] Manhuaus: Update
- [Servers] Phoenix Fansub: Update
- [Servers] Raw Manga: Update
- [Servers] ReadManhwa: Update
- [Servers] ReaperScansFR (GS): Update
- [Servers] Reaper Scans [PT]: Update
- [Servers] AkuManga: Disable
- [Servers] Atikrost: Disable
- [Servers] FR Scan: Disable
- [Servers] Hunlight Scans: Disable
- [Servers] Mangas Origines: Disable
- [Servers] The Nonames Scans: Disable
- [L10n] Updated Finnish and Indonesian translations
> New release 1.20.0

- info.febvre.Komikku.json
- [Reader] LTR/RTL/Vertical pager: Fixed zoom bugs
- [Reader] Fixed crashes caused by corrupted images
- [Servers] Added TCB Scans [EN]
- [Servers] MangaHere: Fixed duplicated pages
- [L10n] Added Arabic and Catalan translations
- [L10n] Updated Dutch and Russian translations
> New release 1.21.0

- info.febvre.Komikku.json
- [Reader] LTR/RTL/Vertical pager: Fixed double tap/click zoom
- [Servers] Jpmangas: Update
- [Servers] Mangaowl: Update
- [L10n] Updated Russian translation
> New release 1.21.1

- info.febvre.Komikku.json
- RTL/LTR/Vertical pager: Added &lt;Crtl+Mouse Wheel&gt; zoom
- [Servers] MangaFreak: Update
- [Servers] Mangapill: Update
- [Servers] Xoxocomics: Update
- [L10n] Updated Arabic, French, Russian and Turkish translations
> New release 1.22.0

- info.febvre.Komikku.json
- [Reader] Full rewrite of the Webtoon pager
- [Servers] Adds PhenixScans [FR]
- [Servers] Adds ToonGod [EN] 
- [Servers] Asura Scans [EN]: Update
- [Servers] FM Team: Update
- [Servers] FR-Scan: Update
- [Servers] Golden Mangás: Update
- [Servers] Grisebouille: Update
- [Servers] MANGA Plus by SHUEISHA: Update
- [Servers] Manga/in/ua: Update
- [Servers] Mangaowl: Update
- [Servers] Union Mangás: Update
- [Servers] Webtoon: Update
- [Servers] Le Cercle du Scan: Disable
- [L10n] Added Romanian translation
- [L10n] Updated Arabic, Catalan, Finnish, Russian and Spanish translations
> New release 1.23.0

- info.febvre.Komikku.json
Bugfix release
[Reader] Webtoon pager: Fixed a scrolling bug
> New release 1.24.2 (bugfix)

- info.febvre.Komikku.json
- python3-lxml.json
- [UX] Refined visuals taking advantage of the new capabilities of GNOME 45
- [Explorer] Global search: Improved speed
- [Servers] Added Perf Scan [FR]
- [Servers] Added Reaper Scans [pt_BR]
- [Servers] Golden Mangás: Update
> New release 1.25.0

- info.febvre.Komikku.json
- [Card] Fixed a bug that occurred during certain `Update` actions
- [Library] Categories sidebar: Added badges to display number of comics per category
> New release 1.25.1

- info.febvre.Komikku.json
- [Library] Added sorting: Alphabetical, Latest Read First (default), Latest Updated First
- [Servers] Mangas Origines [FR]: Reenable
- [Servers] Bilibili Comics: Update
- [Servers] Mangalek: Update
- [Servers] Manhwa Hentai: Update
- [L10n] Updated Finnish, Polish and Spanish translations
> New release 1.26.0

- info.febvre.Komikku.json
- python3-colorthief.json
- [Library] Kept badges in phase with reading status
- [Card] Chapters list: Added `Clear` action (deletes downloaded pages without affecting chapter(s) state)
- [Card] Added backdrop: Background recoloring to match cover
- [Downloader] Improved speed
- [Explorer] Global search: Added a progressbar
- [Explorer] Global search: Added a filter that allows restricting search to pinned servers only
- [Servers] Golden Mangás: Update
- [Servers] MANGA Plus by SHUEISHA: Update
- [Servers] Reaper Scans [PT-br]: Update (name change to `Yugen Scans`)
- [L10n] Updated French, Russian, Spanish and Turkish translations
> New release 1.27.0

- info.febvre.Komikku.json
- [Library] When filtered, it's now correctly updated when changes occur (additions, new chapters, reading progressions)
- [Card] Chapters list: Added missing icon
- [Reader] Fixed chapters ordering while reading
- [UX] In-app notifications: Update to fit GNOME 45 style
- [Webview] Some improvements
- [L10n] Updated Catalan, Polish, Spanish and Turkish translations
> New release 1.27.1

- info.febvre.Komikku.json
- [Card] Chapters list: Fixed "Reset" action not always available
- [Reader] Webtoon pager: Fixed scrolling with touchpad under Wayland
- [Servers] Added LegacyScans [FR]
- [Servers] Flame Comics: Update (rebranded previously Flame Scans)
- [Servers] Fr-Scan: Update
- [Servers] PhenixScans: Update
- [Servers] Yugen Scans: Update
- [L10n] Updated Catalan, Chinese (simplified) and French translations
> New release 1.28.0

- info.febvre.Komikku.json
- [Library] Avoided simultaneous redisplays (lead to thumbnails duplication otherwise)
- [Card] Each time page is redisplayed, scrolling position of subpages (Infos, Chapters, Categories) is now reset to top
- [Servers] MangaReader: Added shuffled images decoding
- [Support] Added a new page to promote donating
> New release 1.30.0

- info.febvre.Komikku.json
- [Reader] Webtoon pager: Fixed scrolling to top and memory leaks
- [Reader] Webtoon pager: Saved reading progress when navigating with slider of controls overlay
- [Servers] Added Honey Manga [UK]
- [Servers] MangaDex: Added Ukrainian
- [L10n] Updated Spanish and Turkish translations
> New release 1.31.0

- info.febvre.Komikku.json
- python3-beautifulsoup4.json
- [Explorer] Search: Add comics covers (when available)
- [UI] Fix broken page navigation when animations are disabled
- [About] Add `Supporters` section
- [Servers] Asura Scans [EN/TR]: Update
- [Servers] Izneo [FR]: Update
- [Servers] Komga: Update
- [Servers] LSComic [EN]: Update (rebranded, previously LeviatanScans)
- [Servers] MangaWorld: Update
- [Servers] Mint Manga: Update
- [Servers] Self Manga: Update
- [L10n] Updated Arabic, French and Turkish translations
> New release 1.32.0

- info.febvre.Komikku.json
- [Servers] Fr-Scan: Update
- [Servers] WEBTOON: Update
- [Servers] Xoxocomics: Update
- [Servers] Golden Mangás [pt_BR]: Disable
- [L10n] Updated Portuguese (Brazil), Spanish and Turkish translations
> New release 1.33.0

- info.febvre.Komikku.json
- [Servers] Comic Book Plus (EN): Update
- [Servers] Honey Manga (UK): Update
- [Servers] Mangalek (AR): Update
- [Servers] Manhwa Hentai (EN): Update
- [Servers] Remanga (RU): Update
- [Servers] Zero Scans (EN): Update
- [Servers] Colored Manga (EN): Disable
- [Servers] Lector Manga (ES): Disable
- [L10n] Updated Indonesian translation
> New release 1.35.0

- info.febvre.Komikku.json
- [Card] Added an indicator when an update is in progress
- [Card] Added Pull-to-Update feature
- [Card] Updated disk usage when one or more chapters are reset
- [Webview] Fixed typo error causing overload
- [About] Fixed "Report an Issue" link
- [Servers] Some improvements to speed up HTML pages parsing
- [Servers] Manga-Scantrad (FR): Fix status CSS selector
- [L10n] Updated Russian translation
> New release 1.37.0

- info.febvre.Komikku.json
- [Card] Added an indicator when an update is in progress
- [Card] Added Pull-to-Update feature
- [Card] Updated disk usage when one or more chapters are reset
- [Webview] Fixed rare cases where pages loading end could not be detected
- [About] Fixed "Report an Issue" link
- [Servers] Some improvements to speed up HTML pages parsing
- [Servers] Manga-Scantrad (FR): Fix status CSS selector
- [L10n] Updated Russian translation
> New release 1.37.1

- info.febvre.Komikku.json
- python3-pure-protobuf.json
- [Library] Added an indicator when an partial update is in progress
- [Servers] Added Mangago (EN)
- [Serverd] Added Rawdevart (JA)
- [L10n] Updated Dutch, Spanish and Turkish translations
> New release 1.39.0

- info.febvre.Komikku.json
- [Servers] Added ComicExtra (EN)
- [Servers] Mangas.in (ES: Update
- [L10n] Updated French, Russian, Spanish and Turkish translations
> New release 1.41.0

- info.febvre.Komikku.json
- [Explorer] Search: Improved covers rendering
- [Updater] Don't attempt to auto-download chapters when a Local source has an update
- [Servers] Added DB New Hope (EN/ES/FR/RU/ZH_Hans)
- [Servers] Added JManga (JA)
- [Servers] Added MangaZin (EN)
- [Servers] Added Read Comics Free (EN)
- [Servers] Apoll Comics (ES): Update
- [Servers] Mangalek (AR): Update
- [Servers] View Comics (EN): Update
- [Servers] Xoxocomics (EN): Update (new site)
- [Servers] Bilibili Comics (EN/ES/FR/ID): Disabled
- [L10n] Updated Finnish, Russian, Spanish and Turkish translations
> New release 1.42.0

- info.febvre.Komikku.json
- Improved downloads and covers display speed
- [Servers] Added Comic Fans (EN)
- [Servers] Added FleksyScans (EN)
- [Servers] Added Iris Scanlator (pt_BR)
- [Servers] Added KomikLovers (ID)
- [Servers] Added Neromax (ID)
- [Servers] Added Scylla Comics (EN)
- [Servers] Added SushiScan (FR)
- [Servers] Added VF Scan (FR)
- [Servers] Legacy Scans (FR): Update
- [Servers] Lelscan-VF (FR): Update
- [Servers] TCB Scans (EN): Update
> New release 1.43.0

- info.febvre.Komikku.json
- [Servers] Added Cartel De Manhwas (ES)
- [Servers] Added F/OSS Comics (EN)
- [Servers] Added Mode Scanlator (pt_BR)
- [Servers] Added Neko Scans (ES)
- [Servers] Added Ragna Scan (ES)
- [Servers] Added Raiki Scan (ES)
- [Servers] Added Rukav Inari (ES)
- [Servers] Added Ryujinmanga (ES)
- [Servers] Added Senpai Ediciones (ES)
- [Servers] Added ShadowMangas (ES)
- [Servers] Added SkyMangas (ES)
- [Servers] Added Tecno Scan (ES)
- [Servers] Added Tres Daos (ES)
- [Servers] Read Manga, Mint Manga, Self Manga (RU): Update
- [Servers] Tapas (EN): Update
- [L10n] Added Hindi translation
- [L10n] Updated Dutch, French and Indonesian translations
> New release 1.44.0

- info.febvre.Komikku.json
- python3-curl_cffi.json
- python3-lxml.json
- python3-pillow.json
- [Webview] Improved Cloudflare user challenge completion
- [Servers] Added Existential Comics (EN)
- [Servers] Added Manga Demon (EN)
- [Servers] Added MangaWeebs (EN)
- [Servers] Added Webtoon TR
- [Servers] Armoni Scans (Asura Scans TR): Reenabled
- [Servers] Atikrost (TR): Reenabled
- [Servers] MangaFreak (EN): Update
- [Servers] Nine Manga (EN/PT_BR/DE/ES/FR/IT/RU): Update
- [L10n] Added Vietnamese translation
- [L10n] Updated French, Portuguese, Spanish and Russian translations
> New release 1.45.0

- info.febvre.Komikku.json
- [Webview] Fixed exiting when there is no Cloudflare challenge
- [Servers] Added MangaCrab (ES)
- [Servers] Comic Book Plus (EN): Update
- [Servers] Mode Scanlator (pt_BR): Update
- [Servers] Rawdevart (JA): Update
- [Servers] ShadowMangas (ES): Update
- [Servers] Tecno Scan (ES): Update
- [Servers] JManga (JA): Disabled
- [L10n] Updated Chinese (Traditional), Dutch, German, Hindi, Italian and Turkish translations
> New release 1.46.0

- info.febvre.Komikku.json
- New feature: Continuously updated servers modules
- [Servers] Added MangaFire (EN/ES/ES_LA/FR/JA/PT/pt_BR)
- [Servers] Re-enabled Argos Comics (PT)
- [Servers] Fr-Scan (FR): Update
- [Servers] Luratoon Scan (pt_BR): Update
- [Servers] Manga/in/ua (UK): Update
- [L10n] Added Swedish translation
- [L10n] Updated Arabic, French, German, Portuguese (Brazil), Spanish and Ukrainian translations
> New release 1.48.0

- info.febvre.Komikku.json
This is a bugfix version
- [Card] Fixed backdrop bug
- [Servers] Local: Fixed wrong location of cover files
- [Servers] Luratoon Scan (pt_BR): Disabled
- [L10n] Updated Dutch, Hindi and Russian translations
> New release 1.48.1

- info.febvre.Komikku.json
- [Servers] Fixed the page to complete Cloudflare challenges
- [Servers] Argos Comics (pt_BR): Update
- [Servers] PhenixScans (FR): Update
- [Servers] TCB Scans (EN): Update
- [Servers] Ragna Scan (ES): Disabled
- [Servers] Tecno Scan (ES): Disabled
- [L10n] Updated Turkish translation
> New release 1.49.0

- info.febvre.Komikku.json
- [Servers] Local: Several bug fixes and improvements
- [Servers] Manga Demon (EN): Update
- [Servers] TCB Scans (EN): Update
- [Servers] FleksyScans (EN): Disabled
> New release 1.50.0

- info.febvre.Komikku.json
- [Servers] Senpai Ediciones (ES): Update
- [Servers] SushiScan (FR): Update
- [L10n] Added Croatian translation
> New release 1.51.0

- info.febvre.Komikku.json
- [Servers] Fixed the page to complete Cloudflare challenges
- [Servers] Japscan (FR): Disabled
- [Servers] Neko Scans (ES): Disabled
- [L10n] Updated Croatian, French and German translations
> New release 1.51.1

- info.febvre.Komikku.json
- python3-curl_cffi.json
- [Servers] Improved webview to complete Cloudflare challenges
- [Servers] Improved webview to support Google ReCAPTCHA completion
- [Servers] ComicExtra (EN): Update
- [Servers] Manga-Scantrad (FR): Update
- [Servers] Mode Scanlator (pt_BR): Update
- [Servers] Asura Scans (EN): Disabled
- [Servers] Mangas Origines (FR): Disabled
- [L10n] Updated French and Ukrainian translations
> New release 1.52.0

- info.febvre.Komikku.json
- [Card] Disabled `Resume` on empty chapters list
- [Reader] Changed interpolation method used to resize images
- [Reader] Improved `Resume`
- [Servers] Asura Scans (EN): Re-enabled
- [Servers] Colored Manga (EN): Re-enabled
- [Servers] Hunlight Scans (EN): Update
- [Servers] Manga Scan (FR): Update
- [Servers] Team-X (AR): Update
- [Servers] Komga: Fixed synchronization
> New release 1.53.0

- info.febvre.Komikku.json
- [Preferences] Reader: Added `Scaling Filter` parameter
- Fixed in-app notification position in fullscreen
- [Servers] Added Anteiku Scans (FR
- [Servers] Added ED Scanlation (FR)
- [Servers] Added EZmanga (EN)
- [Servers] Added Kewn Scans (EN)
- [Servers] Added Starbound Scans (FR)
> New release 1.54.0

- info.febvre.Komikku.json
- [Card] Improved `Resume`
- [Servers] Argos Comics (PT): Update
- [Servers] Armoni Scans (TR): Update
- [Servers] KomikLovers (ID): Update
- [Servers] Manga Tube (DE): Update
- [Servers] MangaWeebs (EN): Update
- [Servers] Rawdevart (JA): Update
- [Servers] View Comics (EN): Update
- [L10n] Updated Hindi and Spanish translations
> New release 1.55.0

- info.febvre.Komikku.json
- [Reader] Fixed display of long strip images
- [Servers] Improved webview CAPTCHAs detection
- [Servers] Improved webview Cloudflare challenges detection
- [Servers] Atikrost (TR): Update
- [Servers] Local: Improved cover generation
- [Servers] Manga Demon (EN): Update
- [Servers] MangaHere (EN): Update
- [Servers] Night scans (EN): Update
- [Servers] SushiScan (FR): Update
- [Servers] VF Scan (FR): Update
- [Servers] Xoxocomics (EN): Update
- [L10n] Updated Croatian and Russian translations
> New release 1.56.0

- info.febvre.Komikku.json
- [Reader] RTL/LTR/Vertical pager: Fixed <Ctrl+mouse wheel> zooming
- [Servers] Argos Comics (PT): Update
- [Servers] MangaHere (EN): Update
> New release 1.57.0

- info.febvre.Komikku.json
- python3-pillow-heif.json
- python3-pillow.json
- [UX] Added system accent colors support
- [Explorer] Fixed Global search
- [Servers] Bentoscan (FR): Disabled
- [Servers] VF Scan (FR): Disabled
> New release 1.59.0

- info.febvre.Komikku.json
- Added Tracking support (AniList, MyAnimeList)
- [Servers] Anteiku Scans (FR): Update
- [Servers] Cerise Scan (pt_BR): Update
- [Servers] ED Scanlation (FR): Update
- [Servers] M440.in (ES): Update
- [Servers] Manga Demon (EN): Update
- [Servers] MangaFreak (EN): Update
- [Servers] Manga-Tube (DE): Update
- [Servers] Scanvf (FR): Fixed search
- [Servers] Sinensistoon (pt_BR): Update
- [Servers] Starbound Scans (FR): Update
- [Servers] Tecno Scans (ES): Update
- [Servers] Colored Manga (EN): Disabled
- [Servers] Read Comics Free (EN): Disabled
- [L10n] Added Bulgarian translation
- [L10n] Updated Dutch, French, Portuguese, Russian, Spanish and Ukrainian translations
> New release 1.60.0

- info.febvre.Komikku.json
- [Tracking] Improved search results
- [Servers] ComicExtra (EN): Update
- [Servers] Honey Manga (UK): Update
- [Servers] Kewn Scans (EN): Update
- [Servers] Manga-Tube (DE): Update
- [Servers] Mint Manga (RU): Update
- [Servers] Read Manga (RU): Update
- [Servers] Self Manga (RU): Update
- [Servers] Tecno Scans (ES): Update
- [L10n] Updated Bulgarian, Finnish, Portuguese (Brazil), Spanish, Turkish and Ukrainian translations
> New release 1.61.0

- info.febvre.Komikku.json
This is a bugfix version.
-  Fixed bad chapter and volume numbers
> New release 1.61.1

- info.febvre.Komikku.json
- [Tracking] Improved dialog size adjustment and handling of errors when query trackers
- [Servers] Terco Scans (ES): Update
- [Servers] Team-X (AR): Update
- [Servers] SushiScan (FR): Update
- [L10n] Updated Bulgarian translation
> New release 1.62.0

- info.febvre.Komikku.json
- [Card] Added `Unread chapters` badge
- [Card] Info: Updated Genres icon
- [Servers] Added Manga Koleji (TR)
- [Servers] Added Webtoon Hatti (TR)
- [Servers] ComicExtra (EN): Disabled
- [Servers] View Comics (EN): Update
- [Servers] Webtoon TR: Update
- [L10n] Updated French, Russian, Spanish and Ukrainian translations
> Ner release 1.65.0

- info.febvre.Komikku.json
- [Reader] Paused pages animations when obscured
- [Servers] Anteiku Scans (FR): Update
- [Servers] Asura Scans For Free (EN): Update
- [Servers] ED Scanlation (FR): Update
- [Servers] Kewn Scans (EN): Update
- [Servers] MonkeyUser (EN): Update
- [Servers] Pepper&amp;Carrot: Update
- [Servers] Starbound Scans (FR): Update
- [Servers] Terco Scans (ES): Update
- [Servers] Webtoon Hatti (TR): Update
- [Servers] Rukav Inari (ES): Disabled
- [Servers] MangaWeebs (EN): Disabled
- [Servers] LSComic (EN): Disabled
- [Servers] Hunlight Scans (EN): Disabled
- [Servers] Mode Scanlator (pt_BR): Disabled
- [Servers] Best Manga (RU): Disabled
- [Servers] Atikrost (TR): Disabled
- [Servers] Perf Scan (FR): Disabled
- [L10n] Updated Bulgarian, German and Polish …
> New release 1.67.0

- info.febvre.Komikku.json
- [Reader] Webtoon pager: Fixed pages jumping on initialization
- [Servers] Added Poseidon Scans (FR)
- [L10n] Added Tamil translation
- [L10n] Updated Chinese (Simplified) and Finnish translations
> New release 1.68.0

- info.febvre.Komikku.json
- python3-dateparser.json
- [Card] Chapters list: Added Scanlators filter
- [Servers] Desu (RU): Update
- [Servers] Lector manga: Re-enabled
- [L10n] Updated Dutch, French, Swedish and Tamil translations
> New release 1.70.0

- info.febvre.Komikku.json
- [Explorer] Global search: Added ability to cancel search
- [Servers] Comic Fans (EN): Disabled
- [Servers] Perf Scan (FR): Re-enabled
- [Servers] TCB Scans (EN): Update
- [Servers] Usagi (RU): Update
- [Servers] Webtoon: Fixed covers
- [L10n] Added Persian translation
- [L10n] Updated French and Russian translations
> New release 1.71.0

- info.febvre.Komikku.json
- [Servers] Added Nix of Nothing (EN)
- [Servers] Added Three Panel Soul (EN)
- [Servers] Added Wild Life (EN)
- [Servers] Cartel De Manhwas (ES): Update
- [Servers] MangaNato (EN): Update
- [Servers] Crunchyroll (EN): Disabled
- [Servers] Iris Scanlator (pt_BR): Disabled
- [Servers] ReaperScans (FR,ID,TR): Disabled
> New release 1.72.0

- info.febvre.Komikku.json
- [Library] Fixed inconsistent background color introduced in previous version
- [Servers] Aurora Scan (pt_BR): Disabled
- [Servers] Noromax (ID): Update
- [Servers] Tecno Scans (EN): Update
- [Servers] Wicked Witch Scan (pt_BR): Disabled
- [Servers] `Up-to-date modules` feature: an app restart is now required for a change to take effect (modules update or setting activation/deactivation)
- [L10n] Updated Bulgarian, Czech, French, Russian and Ukrainian translations
> New release 1.74.0

- info.febvre.Komikku.json
- python3-curl_cffi.json
- [Servers] ريبر العربي (AR): Disabled
- [Servers] 3asq (AR): Disabled
- [Servers] Dango Scan (pt_BR): Update
- [Servers] DB New Hope (EN/ES/FR): Update
- [Servers] Dynasty Reader (EN): Update
- [Servers] EZmanga (EN): Ignored chapters with price
- [Servers] Mangaowl (EN): Update
- [Servers] MangaReader (EN): Update
- [Servers] Manhwa Hentai (EN): Disabled
- [Servers] Mint Manga (RU): Disabled
- [Servers] Nazarick Scan (pt_BR): Update
- [Servers] PhenixScans (FR): Update
- [Servers] View Comics (EN): Update
- [Servers] Xoxocomics (EN): Update
- [L10n] Updated French and Russian translations
> New release 1.75.0

- info.febvre.Komikku.json
This is a bugfix version.
- [Reader] Webtoon mode: Fixed scrolling after a pages jump (using controls overlay)
- [L10n] Updated Portuguese (Brazil) translation
> New release 1.76.1

- info.febvre.Komikku.json
- [Webview] Fixed Cloudflare challenge detection
- [Servers] Manga-Scantrad (FR): Update
- [Servers] Night scans (EN): Update
- [Servers] Mangapill (EN): Update
- [L10n] Updated Spanish translation
> New relase 1.77.0

- info.febvre.Komikku.json
- [Card] Added new backdrop method: Blurred cover
- [Servers] MangaMana (FR): Update
- [Servers] MangaNato (EN): Update
- [Servers] Mangaowl (EN): Update
- [Servers] MangaReader (cc) (EN): Update
- [Servers] Neko Scans(ES): Update
- [Servers] Pepper&amp;Carrot: Added support of Persian language
- [Servers] Rawdevart (JA): Update
- [Servers] Senpai Ediciones (ES): Disabled
- [Servers] Usagi (RU): Disabled
- [L10n] Updated Arabic and Persian translations
> New release 1.79.0

- info.febvre.Komikku.json
This is a bugfix version.
- [Card] Fixed Pull-to-Update
> New release 1.79.1

- info.febvre.Komikku.json
- [Card] Pool-to-Update: Improved spinner visibility
- [Servers] Added ComicK (comick.io)
- [Servers] Added Raijin Scan (FR)
- [Servers] Pepper &amp; Carrot: Update
- [Servers] Phenix Scans (FR): Update
- [Servers] Mangalek (AR): Update
- [Servers] WEBTOON (EN/ES/FR/ID/TH/ZH): Update
- [L10n] Updated French and Persian translations
> New release 1.80.0

- info.febvre.Komikku.json
- python3-brotli.json
- python3-dateparser.json
- python3-emoji.json
- python3-pillow.json
- python3-requests.json
- [Card] Improved interface refresh after an update
- [Updater] Added detection of downed servers (avoids unnecessary manga updates)
- [Servers] ComicK: Fixed covers in search results
- [Servers] Mangalek (AR): Update
- [Servers] NHentai (EN/JA/ZH): Update
- [Servers] Rawkuma (JA): Update
- [Servers] WEBTOON: Update
- [L10n] Added Lithuanian translation
- [L10n] Updated French, Italian, Russian, Tamil and Ukrainian translations
> New release 1.81.0

- info.febvre.Komikku.json
- python3-curl_cffi.json
- python3-requests.json
- [Servers] Added MANGA Plus Creators by SHUEISHA (EN/ES)
- [Servers] Cartel De Manhwas (ES): Update
- [Servers] Lectormanga (ES): Update
- [Servers] MangaLib (RU): Update
- [Servers] Raw Manga (JA): Disabled
- [Servers] ToonGod (EN): Update
- [Servers] Webtoon Hatti (TR): Update
- [L10n] Updated Arabic and Bulgarian translations
> New release 1.83.0

- info.febvre.Komikku.json
- [Reader] Added ability to apply filters to pages (brightness, contrast, grayscale, sepia, saturation)
- [Reader] RTL/LTR/Vertical pager: Added keyboard zoom
- [Reader] Webtoon pager: Fixed weird jumps during backward scrolling
- [L10n] Updated Arabic and French translations
> New release 1.84.0

- info.febvre.Komikku.json
- [Library] Added `F9` shortcut to open `Categories` pane
- [Servers] Added Invincible ComicsVF (FR)
- [Servers] ComicHubFree (EN): Update
- [Servers] Desu (RU): Update
- [L10n] Updated Arabic, French and Russian translations
> New release 1.85.0

- info.febvre.Komikku.json
- [Servers] Cartel De Manhwas (ES): Update
- [Servers] Mangapill: Update
- [Servers] SCtoon (pt_BR): Disabled
- [Servers] Starbound Scans (FR): Update
- [L10n] Updated Arabic, Croatian, Finnish and  Portuguese (Brazil) translations
> New release 1.87.0
